### ISSUE TITLE
feedback on the `toolbar` control

### ISSUE THREAD

**Issue by devoncarew** [dart-atom/atom-toolbar#1]
This issue can track feedback on the utility of a `toolbar` control. It'll be used for some top-level buttons and custom controls that need some UI space, but that don't feel right in a status-line area. Some examples:
- forward and backwards navigation buttons, when jump to a definition and jumping back
- visualizing when you are connected to devices (mobile devices) - selecting a default device
- perhaps awareness of currently running applications (user apps which were launched)

**Comment by devoncarew** [comment]
<img width="842" alt="screen shot 2015-07-29 at 9 53 49 pm" src="https://cloud.githubusercontent.com/assets/1269969/8976056/5a4ebb38-363c-11e5-8621-3a11dbb5e1f8.png">

<img width="402" alt="screen shot 2015-07-29 at 9 54 17 pm" src="https://cloud.githubusercontent.com/assets/1269969/8976060/6284b7c6-363c-11e5-94bc-59bc1283c353.png">

**Comment by sethladd** [comment]
> forward and backwards navigation buttons, when jump to a definition and jumping back

There's a plugin for this. So the high-level question is... how important is it to add buttons to the UI of Atom? Is that Atom-y ? Or are command palette and key combos sufficient?

**Comment by devoncarew** [comment]
I need a place to visualize connected devices, and probably running applications. I don't think the status bar has enough visibility. It may be that we don't end up needing a toolbar, but it's how I want to start off exploring the UI.

**Comment by sethladd** [comment]
> I need a place to visualize connected devices, and probably running applications

Ah, yeah! Makes sense.

**Comment by devoncarew** [comment]
landed! closing...
